export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
export const FETCH_USER = "FETCH_USER";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const SET_BASE_CURRENCY = "SET_BASE_CURRENCY";
